version: "3"
services:
  backend:
    build:
      context: ./backend
      dockerfile: ./dockerfile
    networks:
    - nat
    restart: always

  front:
    image: nginx:latest
    networks:
    - nat
    restart: always
    volumes:
    - ./front/data/certbot/conf:/etc/letsencrypt
    - ./front/default.conf:/etc/nginx/conf.d/default.conf
    - ./front/html:/html
    ports:
    - 80:80
    - 443:443

networks:
  nat: